apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-base
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: <ваш-репо>
    path: charts/infra # чарты с nginx/nfs, либо plain манифесты
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-nfs
  syncPolicy:
    automated:
      prune: true       # удалять ресурсы, если их нет в Git
      selfHeal: true    # исправлять ручные правки
    syncOptions:
      - CreateNamespace=true