apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/oaufqas/argocd-infrastructure-repo
    path: charts/ingress-nginx/
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true       # удалять ресурсы, если их нет в Git
      selfHeal: true    # исправлять ручные правки
    syncOptions:
      - CreateNamespace=true