injector:
  enabled: false

server:
  dev:
    enabled: false
  ha:
    enabled: true
    replicas: 1
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true
        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }
        storage "raft" {
          path = "/vault/data"
        }
        seal "yandexcloudkms" {
          kms_key_id = "abjvlc2rtvg7cfo3n8q0"
        }
  # image:
  #   repository: mirror.gcr.io/hashicorp/vault
    tag: 1.15.0
  dataStorage:
    enabled: true
    size: 3Gi