server:
  name: server
  replicas: 2
  container:
    name: rent
    port: 5000
    image: rvlxx/rent
    tag: "cec973be"
  serviceName: server-svc
  imagesecret: registry-secret
  scname: nfs
  pvcname: server-shared-storage
  storage: 3Gi
  appsecret: server-values
  # saname: server-sa
db:
  name: mysql
  image: mysql:8.0
  dbsecret: secret-variables
  cfgmysqlconf: config-mysql
  cfgmysqlinit: initssql
  storage: 1Gi
  saname: db-sa
ssl:
  enabled: true
  domain: kycaka.com
  email: zxcvbn@gmail.com
  certname: cert-tls
  secretname: secret-tls
  issuername: letsencrypt-issuer
