nameOverride: "vm"
fullnameOverride: "vm"

grafana:
  enabled: true
  adminPassword: "admin"
  plugins:
    - "victoriametrics-logs-datasource"
defaultDatasources:
  extra: 
    - name: VictoriaLogs
      type: victoriametrics-logs-datasource
      access: proxy
      url: http://victoria-logs-server.monitoring:9428

vmsingle:
  enabled: true
  spec:
    retentionPeriod: "14d"
    storage:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "yc-network-hdd" 
      resources:
        requests:
          storage: 2Gi
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"

prometheus-node-exporter:
  service:
    port: 9100
    targetPort: 9100
  serviceMonitor:
    enabled: true
    additionalLabels:
      vmagent: "vm"
      release: "victoria-metrics"