apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps/applications/cert-manager.yaml
  - apps/applications/external-secrets.yaml
  - apps/applications/ingress-nginx.yaml
  - apps/applications/nfs-server.yaml
  - apps/applications/vault.yaml
  - appsapplications/app.yaml