apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - applications/cert-manager.yaml
  - applications/external-secrets.yaml
  - applications/ingress-nginx.yaml
  - applications/nfs-server.yaml
  - applications/vault.yaml
  - applications/app.yaml