apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: https://github.com/oaufqas/argocd-infrastructure-repo
    targetRevision: master
    path: charts/nfs-server-provisioner/
    helm: 
      values: |
        persistence: 
          enabled: true
          size: 4Gi
          storageClass: "yc-network-hdd"
        storageClass:
          name: nfs
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 3m 
    syncOptions:
      - CreateNamespace=true